### PR TITLE
pickle: date type

### PR DESCRIPTION
**Pull request by dalonso82**
This fix is about 
https://github.com/anguenot/pyspark-cassandra/issues/19
https://github.com/anguenot/pyspark-cassandra/issues/21

it seems TypeConverter.scala doesn't work propertly into pyspark_cassandra.
I've defined several pickle about date to fix those issues

### CODE REVIEW

**Comment by jbjose** [comment]
This works for me.

**Comment by anguenot** [comment]
Hey @dalonso82 , 

Sorry about the delay on this. Think we could get some tests added before merging it? 

What Spark versions have you been testing that PR against on your end?

Thanks!

**Comment by dalonso82** [comment]
Hi @anguenot 
The test about date type has been added, but according to the design of tests, it's not supported by cassandra version 2.1.21 because of the date is a reserved word.

do we refactor the tests? or do we remove the test about cassandra version 2.1.21?

**Comment by anguenot** [comment]
@dalonso82  mind refactoring the tests? I believe they are still quite a few users of Cassandra 2.1.x these days.

**Comment by dalonso82** [comment]
According to datastax the cassandra version 2.1 is not supported:
      https://docs.datastax.com/en/archived/cql/3.1/cql/cql_reference/cql_data_types_c.html
And in this version does not exist this data type
According to Apache:
      Apache Cassandra 2.1 is supported until 4.0 release (date TBD) with critical fixes only.

So I don't know how we could keep cassandra version 2.1

**Comment by anguenot** [comment]
@dalonso82  I see. Well, time to drop 2.1 support here then. Let me prepare a PR and get rid of it on master, Then we can rebase and we should be good to go. Thanks

**Pull request merged**
